name: PR Comment

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - unlocked

jobs:
  pr-comment:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: mshick/add-pr-comment@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message-id: pr-comment
          message: |
            Thanks for your contribution.

            The next step is to wait for review and approval to merge it to main repository

            The community can help reacting with a thumb up (:thumbsup:) for approval and rocket (:rocket:) for who has tested it.
          message-failure: |
            Your PR failed, please check it before continuing to the next step.
